### ISSUE TITLE
stable_sort_each.inl doesn't compile with opencv 3.2

### ISSUE THREAD

**Issue by nnorwitz** [NVIDIA/thrust#883]
When trying to build opencv 3.2, I get a build error when building modules/cudaimgproc/src/cuda/gftt.cu  I don't really know if this is a problem with opencv or thrust.  The compilation error is:

./third_party/thrust/thrust/system/cuda/detail/detail/stable_sort_each.inl.h(60): error: calling a __host__ function("std::swap< ::float2> ") from a __device__ function("thrust::system::cuda::detail::detail::stable_sort_each_detail::static_stable_odd_even_transpose_sort_detail::impl<(int)1, (int)7> ::do_it< ::float2 *, ::thrust::detail::wrapped_function< ::cvx::cuda::device::gfft::EigGreater, bool> > ") is not allowed

I can fix the compilation by changing:
 https://github.com/thrust/thrust/blob/master/thrust/system/cuda/detail/detail/stable_sort_each.inl#L58

from:
using thrust::swap;
swap(...);

to:

thrust::swap(...);

This may not be the best fix, but it fixed my problem.  I wanted to at least let you guys know about the issue.  Let me know if you need more info.

**Comment by nnorwitz** [comment]
Sorry, I forgot to mention that I'm using nvcc to compile.

**Comment by brycelelbach** [comment]
Hi,

What operating system, compiler version and CUDA version where you using?

**Comment by nnorwitz** [comment]
I'm building on Ubuntu 14.04, using nvcc 4.8.5 for CUDA 8.  

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

**Comment by brycelelbach** [comment]
Okay, I will take a look.

**Comment by brycelelbach** [comment]
Hey @nnorwitz,

Thrust 1.9.0 - aka the version of Thrust in CUDA 9.0, which we recently released - has a new CUDA backend, including a new implementation of our sorting algorithms.

ATM, Thrust 1.9.0 is not in Github, so can I ask you to try upgrading to CUDA 9.0 and see if you can reproduce this issue? Note that you will need to upgrade your NVIDIA linux kernel driver as well (to at least r384).

You can download
[the driver here](http://www.nvidia.com/Download/index.aspx?lang=en-us) and [the toolkit here](https://developer.nvidia.com/cuda-downloads).

I am not sure if .deb packages for CUDA 9.0 have landed in the main Ubuntu repos yet; I haven't seen them in Debian.
