### ISSUE TITLE
transform_inclusive_scan compilation error with CUDA 11.4

### ISSUE THREAD

**Issue by cwsmith** [NVIDIA/thrust#1506]
Hello,

The test code described in the opening post of issue #1332 does not successfully compile with Thrust included with CUDA 11.4 using the following command.

```
nvcc -ccbin=g++-10 -arch=sm_75 dan.cu -o dan
```

The first portion of the compilation error is listed below.

```
/opt/cuda/bin/../targets/x86_64-linux/include/cub/device/dispatch/../../agent/agent_scan.cuh(294): error: const variable "items" requires an initializer
          detected during:
            instantiation of "void cub::AgentScan<AgentScanPolicyT, InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT>::ConsumeTile<IS_LAST_TILE>(OffsetT, int, OffsetT, cub::AgentScan<AgentScanPolicyT, InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT>::ScanTileStateT &) [with AgentScanPolicyT=cub::AgentScanPolicy<128, 12, const LO, cub::BLOCK_LOAD_DIRECT, cub::LOAD_LDG, cub::BLOCK_STORE_WARP_TRANSPOSE_TIMESLICED, cub::BLOCK_SCAN_RAKING, cub::MemBoundScaling<128, 12, const LO>>, InputIteratorT=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, OutputIteratorT=LO *, ScanOpT=thrust::maximum<LO>, InitValueT=cub::NullType, OffsetT=thrust::detail::int32_t, IS_LAST_TILE=false]" 
(355): here 
            instantiation of "void cub::AgentScan<AgentScanPolicyT, InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT>::ConsumeRange(OffsetT, cub::AgentScan<AgentScanPolicyT, InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT>::ScanTileStateT &, int) [with AgentScanPolicyT=cub::AgentScanPolicy<128, 12, const LO, cub::BLOCK_LOAD_DIRECT, cub::LOAD_LDG, cub::BLOCK_STORE_WARP_TRANSPOSE_TIMESLICED, cub::BLOCK_SCAN_RAKING, cub::MemBoundScaling<128, 12, const LO>>, InputIteratorT=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, OutputIteratorT=LO *, ScanOpT=thrust::maximum<LO>, InitValueT=cub::NullType, OffsetT=thrust::detail::int32_t]" 
/opt/cuda/bin/../targets/x86_64-linux/include/cub/device/dispatch/dispatch_scan.cuh(131): here 
            instantiation of "void cub::DeviceScanKernel<ScanPolicyT,InputIteratorT,OutputIteratorT,ScanTileStateT,ScanOpT,InitValueT,OffsetT>(InputIteratorT, OutputIteratorT, ScanTileStateT, int, ScanOpT, InitValueT, OffsetT) [with ScanPolicyT=cub::AgentScanPolicy<128, 12, const LO, cub::BLOCK_LOAD_DIRECT, cub::LOAD_LDG, cub::BLOCK_STORE_WARP_TRANSPOSE_TIMESLICED, cub::BLOCK_SCAN_RAKING, cub::MemBoundScaling<128, 12, const LO>>, InputIteratorT=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, OutputIteratorT=LO *, ScanTileStateT=cub::ScanTileState<const LO, true>, ScanOpT=thrust::maximum<LO>, InitValueT=cub::NullType, OffsetT=thrust::detail::int32_t]" 
/opt/cuda/bin/../targets/x86_64-linux/include/cub/device/dispatch/dispatch_scan.cuh(396): here 
            instantiation of "cudaError_t cub::DispatchScan<InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT, SelectedPolicy>::Invoke<ActivePolicyT>() [with InputIteratorT=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, OutputIteratorT=LO *, ScanOpT=thrust::maximum<LO>, InitValueT=cub::NullType, OffsetT=thrust::detail::int32_t, SelectedPolicy=cub::DeviceScanPolicy<const LO>, ActivePolicyT=cub::DeviceScanPolicy<const LO>::Policy350]" 
/opt/cuda/bin/../targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh(706): here 
            instantiation of "cudaError_t cub::ChainedPolicy<PTX_VERSION, PolicyT, PolicyT>::Invoke(int, FunctorT &) [with PTX_VERSION=350, PolicyT=cub::DeviceScanPolicy<const LO>::Policy350, FunctorT=cub::DispatchScan<thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, LO *, thrust::maximum<LO>, cub::NullType, thrust::detail::int32_t, cub::DeviceScanPolicy<const LO>>]" 
/opt/cuda/bin/../targets/x86_64-linux/include/cub/block/../iterator/../util_device.cuh(689): here 
            [ 2 instantiation contexts not shown ]
            instantiation of "cudaError_t cub::DispatchScan<InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT, SelectedPolicy>::Dispatch(void *, size_t &, InputIteratorT, OutputIteratorT, ScanOpT, InitValueT, OffsetT, cudaStream_t, __nv_bool) [with InputIteratorT=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, OutputIteratorT=LO *, ScanOpT=thrust::maximum<LO>, InitValueT=cub::NullType, OffsetT=thrust::detail::int32_t, SelectedPolicy=cub::DeviceScanPolicy<const LO>]" 
/opt/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/scan.h(78): here 
            instantiation of "OutputIt thrust::cuda_cub::detail::inclusive_scan_n_impl(thrust::cuda_cub::execution_policy<Derived> &, InputIt, Size, OutputIt, ScanOp) [with Derived=thrust::cuda_cub::par_t, InputIt=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, Size=std::ptrdiff_t, OutputIt=LO *, ScanOp=thrust::maximum<LO>]" 
/opt/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/scan.h(228): here 
            instantiation of "OutputIt thrust::cuda_cub::inclusive_scan_n(thrust::cuda_cub::execution_policy<Derived> &, InputIt, Size, OutputIt, ScanOp) [with Derived=thrust::cuda_cub::par_t, InputIt=thrust::cuda_cub::transform_input_iterator_t<const LO, LO *, thrust::identity<LO>>, Size=std::ptrdiff_t, OutputIt=LO *, ScanOp=thrust::maximum<LO>]" 
/opt/cuda/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/transform_scan.h(74): here 
            instantiation of "OutputIt thrust::cuda_cub::transform_inclusive_scan(thrust::cuda_cub::execution_policy<Derived> &, InputIt, InputIt, OutputIt, TransformOp, ScanOp) [with Derived=thrust::cuda_cub::par_t, InputIt=LO *, OutputIt=LO *, TransformOp=thrust::identity<LO>, ScanOp=thrust::maximum<LO>]" 
/opt/cuda/bin/../targets/x86_64-linux/include/thrust/detail/transform_scan.inl(47): here 
            instantiation of "OutputIterator thrust::transform_inclusive_scan(const thrust::detail::execution_policy_base<DerivedPolicy> &, InputIterator, InputIterator, OutputIterator, UnaryFunction, AssociativeOperator) [with DerivedPolicy=thrust::cuda_cub::par_t, InputIterator=LO *, OutputIterator=LO *, UnaryFunction=thrust::identity<LO>, AssociativeOperator=thrust::maximum<LO>]" 
dan.cu(23): here 
```

**Comment by allisonvacanti** [comment]
Can confirm that this issue still exists: https://www.godbolt.org/z/hdq5e91od

**Comment by jrhemstad** [comment]
Simplified repro: https://www.godbolt.org/z/d6WWvv7ce

It looks like the issue is caused by the fact that `thrust::identity::operator()` returns a `const&`. I suspect somewhere inside CUB where we're querying the return type we need to add a `std::remove_ref_t`.

**Comment by senior-zero** [comment]
@jrhemstad CUB decays accumulator type, the issue is on the Thrust side. I'll create a PR that addresses the issue today.

**Comment by jrhemstad** [comment]
For reference, I found that if I make the repro conform with how `std::identity` works by returning `T&&` and `std::forward<T>(t)` then it works: https://www.godbolt.org/z/o7TbnWbzW
